package org.mobilitydb.kafka.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TAlpha
 * Methods emitted: 1 (bounded-state=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;

public final class MeosOpsTAlpha {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTAlpha() { /* utility */ }

    /**
     * MEOS {@code talpha_type} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static boolean talpha_type(int arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "talpha_type requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.talpha_type(arg0);
    }

}
