package org.mobilitydb.kafka.meos;

/* AUTO-GENERATED by codegen_flink_v3.py — do not edit by hand.
 * MEOS object-model class: TRGeometry
 * Methods emitted: 36 (bounded-state=32 · stateless=3 · io-meta=1)
 * Source: JMEOS jar (PR #15 / regen-against-meos-1.4) ∩ streaming-relevance baseline v4.
 */

import functions.GeneratedFunctions;
import java.time.OffsetDateTime;
import jnr.ffi.Pointer;

public final class MeosOpsTRGeometry {

    public static final boolean MEOS_AVAILABLE = MeosOpsRuntime.MEOS_AVAILABLE;

    private MeosOpsTRGeometry() { /* utility */ }

    /**
     * MEOS {@code trgeometry_to_tinstant} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer trgeometry_to_tinstant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tinstant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tinstant(arg0);
    }

    /**
     * MEOS {@code trgeometry_to_tpoint} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer trgeometry_to_tpoint(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tpoint requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tpoint(arg0);
    }

    /**
     * MEOS {@code trgeometry_to_tpose} — tier <b>stateless</b>.
     * <p>Pure per-event; safe in any Flink scalar position.</p>
     * <p>Object-model role: {@code conversion}.</p>
     * <p>Classification: role=conversion</p>
     */
    public static Pointer trgeometry_to_tpose(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_to_tpose requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_to_tpose(arg0);
    }

    /**
     * MEOS {@code trgeometry_after_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_after_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_after_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_after_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_append_tinstant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_append_tinstant(Pointer arg0, Pointer arg1, int arg2, double arg3, Pointer arg4, boolean arg5) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_append_tinstant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_append_tinstant(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    /**
     * MEOS {@code trgeometry_append_tsequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_append_tsequence(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_append_tsequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_append_tsequence(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_before_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_before_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_before_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_before_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_delete_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_delete_tstzset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_delete_tstzspan(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzspan(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_delete_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_delete_tstzspanset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_delete_tstzspanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_delete_tstzspanset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_end_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_end_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_instant(arg0);
    }

    /**
     * MEOS {@code trgeometry_end_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_end_sequence(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_sequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_sequence(arg0);
    }

    /**
     * MEOS {@code trgeometry_end_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_end_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_end_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_end_value(arg0);
    }

    /**
     * MEOS {@code trgeometry_geom} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_geom(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_geom requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_geom(arg0);
    }

    /**
     * MEOS {@code trgeometry_instant_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_instant_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_instant_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_instant_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_instants} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_instants(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_instants requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_instants(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_points} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_points(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_points requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_points(arg0);
    }

    /**
     * MEOS {@code trgeometry_restrict_timestamptz} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_timestamptz(Pointer arg0, OffsetDateTime arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_timestamptz requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_timestamptz(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_tstzset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzspan} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_tstzspan(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzspan requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzspan(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_tstzspanset} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_tstzspanset(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_tstzspanset requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_tstzspanset(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_value(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_value(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_restrict_values} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_restrict_values(Pointer arg0, Pointer arg1, boolean arg2) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_restrict_values requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_restrict_values(arg0, arg1, arg2);
    }

    /**
     * MEOS {@code trgeometry_rotation} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_rotation(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_rotation requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_rotation(arg0);
    }

    /**
     * MEOS {@code trgeometry_round} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_round(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_round requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_round(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_segments} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_segments(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_segments requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_segments(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_sequence_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_sequence_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_sequence_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_sequence_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_sequences} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_sequences(Pointer arg0, Pointer arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_sequences requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_sequences(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_set_interp} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_set_interp(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_set_interp requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_set_interp(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_start_instant} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_start_instant(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_instant requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_instant(arg0);
    }

    /**
     * MEOS {@code trgeometry_start_sequence} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_start_sequence(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_sequence requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_sequence(arg0);
    }

    /**
     * MEOS {@code trgeometry_start_value} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_start_value(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_start_value requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_start_value(arg0);
    }

    /**
     * MEOS {@code trgeometry_traversed_area} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_traversed_area(Pointer arg0, boolean arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_traversed_area requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_traversed_area(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_value_n} — tier <b>bounded-state</b>.
     * <p>Per-event with bounded per-key state (MEOS handle).</p>
     * <p>Object-model role: {@code accessor}.</p>
     * <p>Classification: role=accessor</p>
     */
    public static Pointer trgeometry_value_n(Pointer arg0, int arg1) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_value_n requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_value_n(arg0, arg1);
    }

    /**
     * MEOS {@code trgeometry_out} — tier <b>io-meta</b>.
     * <p>I/O / catalog / lifecycle helper.</p>
     * <p>Object-model role: {@code output}.</p>
     * <p>Classification: IO/serialization</p>
     */
    public static String trgeometry_out(Pointer arg0) {
        if (!MEOS_AVAILABLE) {
            throw new UnsupportedOperationException(
                "trgeometry_out requires libmeos — set -Dmobilityflink.meos.enabled=true");
        }
        return GeneratedFunctions.trgeometry_out(arg0);
    }

}
